### ISSUE TITLE
MongoDB uses milliseconds for DateTime while Julia uses seconds

### ISSUE THREAD

**Issue by turtleslow** [pzion/LibBSON.jl#16]
Peter, great work on the LIbBSON / Mongo drivers!  DateTimes didn't seem to make it into the last release, so I looked at adding the functionality and noticed that you basically have it implemented in your master branch.  However, there seems to be a small inconsistency at the moment since MongoDB uses milliseconds and Julia uses seconds.

For reference see:
https://docs.mongodb.org/manual/reference/bson-types/#date
http://docs.julialang.org/en/release-0.4/stdlib/dates/#Dates.unix2datetime

I believe the simple fixes below should do the trick:

**In  LibBSON.jl/src/BSONIter.jl:**
```julia
        elseif ty == BSON_TYPE_DATE_TIME
        ts = ccall(
            (:bson_iter_date_time, libbson),
            Int64, (Ptr{UInt8}, ),
            bsonIter._wrap_
            ) / 1000  # millisecond to second conversion
        return Dates.unix2datetime(ts)
```

**In  LibBSON.jl/src/BSONObject.jl:**
```julia
function append(bsonObject::BSONObject, key::AbstractString, val::Union{Date,DateTime})
    keyCStr = bytestring(key)
    ts = typeof(val) == Date ? datetime2unix(DateTime(val)) : datetime2unix(val)
    ccall(
        (:bson_append_date_time, libbson),
        Bool, (Ptr{Void}, Ptr{UInt8}, Cint, Clong),
        bsonObject._wrap_,
        keyCStr,
        length(keyCStr),
        ts * 1000   # second to millisecond conversion
        ) || error("libBSON: overflow")
```

**In  LibBSON.jl/src/BSONArray.jl:**
```julia
function append(bsonArray::BSONArray, val::Union{Date,DateTime})
    keyCStr = bytestring(string(length(bsonArray)))
    ts = typeof(val) == Date ? datetime2unix(DateTime(val)) : datetime2unix(val)
    ccall(
        (:bson_append_date_time, libbson),
        Bool, (Ptr{Void}, Ptr{UInt8}, Cint, Clong),
        bsonArray._wrap_,
        keyCStr,
        length(keyCStr),
        ts * 1000   # second to millisecond conversion
        ) || error("libBSON: overflow")
end
```

Turtle

**Comment by pzion** [comment]
Hi there, sorry for the delay on this.  I just merged a pull request that should take care of this problem.  Happy holidays!
