### ISSUE TITLE
Convert BSONObject to Dict

### ISSUE THREAD

**Issue by ianshmean** [pzion/LibBSON.jl#20]
I feel like there's a very simple answer to this, but I can't figure it out. How can I convert a BSONObject into a Dict with the same structure/content?

If I'm not missing something incredibly simple, it may be worth adding it as an example.

(I'm working with Mongo.jl trying to extract a Dict, modify it and re-add it. To do that I have to re-add it as a Dict)

**Comment by pzion** [comment]
I think this is one of the cases in the unit tests:

```
    @fact dict(bsonObject) --> @compat Dict{Any,Any}("string"=>"Hello, Jérôme","anotherNull"=>nothing,"null"=>nothing,"regularSymbol"=>"symbol","bool"=>true,"int"=>42,"minkey"=>:minkey,"maxkey"=>:maxkey,"array"=>Any["hello",(@compat Dict{Any,Any}("foo"=>Any[56,false]))],"subdict"=>(@compat Dict{Any,Any}("key"=>"value")),"double"=>3.141000)
```

So, I think just using the `dict(bsonObject)` syntax should do it. 

I agree that if it's not obvious it would be a good idea to add it to the docs, which at this point is the README file.  Care to submit a pull request? :-)

**Comment by pzion** [comment]
Closing as this appears to be dead
