### ISSUE TITLE
How to get dates out of a BSONObject

### ISSUE THREAD

**Issue by szalmaf** [pzion/LibBSON.jl#5]
If the following BSONObject is returned from a (Mongo) database, how to get the "d" date out of this object, at least the unix date integer?

BSONObject({ "_id" : { "$oid" : "55d8f6b1f69dbaebaacd7e58" }, "d" : { "$date" : 1438628400000 }, "f" : 0.25., "s": "hello" })

**Comment by tmlbl** [comment]
This should be fixed by #13
